theme: jekyll-theme-minimal
logo: https://www.mayo.edu/-/media/kcms/gbs/research/images/2019/02/06/15/18/genetics-bioinformatics-shu-571040611-8col.jpg
title: Achyuta's Bioinformatics Class (BIMM 143, Fall 2024)
